# Generated by Django 5.1.7 on 2025-03-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikipediaCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField()),
                ('image_url', models.URLField(unique=True)),
                ('caption', models.TextField()),
            ],
        ),
    ]
