# Generated by Django 5.1.7 on 2025-03-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_imagecaption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageCaption',
        ),
        migrations.DeleteModel(
            name='WikipediaPage',
        ),
    ]
