name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Docker CLI and Docker Compose
      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      # Login to Azure Blob Storage using environment secrets
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build Docker images with Docker Compose
      - name: Build Docker images
        run: |
          docker compose build

      # List Docker images to verify
      - name: List Docker images
        run: docker images

      # Save all Docker images as a .tar file
      - name: Save Docker images to tar
        run: |
          docker save -o chakshuv1.tar \
            $(docker images --format "{{.Repository}}:{{.Tag}}" | grep -E "chakshu|ollama|latex_to_text")

      # Verify the .tar file
      - name: Verify saved Docker image
        run: |
          ls -lh chakshuv1.tar

      # Upload the .tar file to Azure Blob Storage
      - name: Upload image to Azure Blob Storage
        run: |
          az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --container-name ${{ secrets.AZURE_CONTAINER_NAME }} \
            --name chakshuv1.tar \
            --file chakshuv1.tar \
            --auth-mode key \
            --overwrite
