name: Build, Push Docker Images & Deploy with Static IP + HTTPS on Azure ACI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Docker & Docker-Compose
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        docker --version
        docker compose version

    - name: Create .env file
      run: |
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env

    - name: Build Docker Images
      run: |
        docker compose build

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Tag and Push Docker Images
      run: |
        USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
        
        # Tag images
        docker tag chakshu-chakshu:latest $USERNAME/chakshu-chakshu:latest
        docker tag chakshu-node:latest $USERNAME/chakshu-node:latest

        # Push images to Docker Hub
        docker push $USERNAME/chakshu-chakshu:latest
        docker push $USERNAME/chakshu-node:latest

    - name: Azure Login
      run: |
        az login --service-principal \
          --username "${{ secrets.AZURE_CLIENT_ID }}" \
          --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
          --tenant "${{ secrets.AZURE_TENANT_ID }}"

    - name: Check or Create Static IP
      run: |
        RESOURCE_GROUP="${{ secrets.AZURE_RESOURCE_GROUP }}"
        STATIC_IP_NAME="chakshu-static-ip"

        # Check if Static IP exists
        IP_EXISTS=$(az network public-ip show --resource-group "$RESOURCE_GROUP" --name "$STATIC_IP_NAME" --query "ipAddress" --output tsv || echo "")

        if [ -z "$IP_EXISTS" ]; then
          echo "Static IP not found. Creating..."
          az network public-ip create \
            --resource-group "$RESOURCE_GROUP" \
            --name "$STATIC_IP_NAME" \
            --sku Standard \
            --allocation-method Static \
            --query "publicIp.ipAddress" --output tsv

          # Wait for the IP to be provisioned
          sleep 30

          STATIC_IP=$(az network public-ip show --resource-group "$RESOURCE_GROUP" --name "$STATIC_IP_NAME" --query "ipAddress" --output tsv)
          echo "Static IP created: $STATIC_IP"
        else
          STATIC_IP="$IP_EXISTS"
          echo "Using existing Static IP: $STATIC_IP"
        fi

        echo "STATIC_IP=$STATIC_IP" >> $GITHUB_ENV

    - name: Deploy to Azure ACI with Static IP
      run: |
        CONTAINER_NAME="chakshu-container"
        RESOURCE_GROUP="${{ secrets.AZURE_RESOURCE_GROUP }}"
        STATIC_IP="${{ env.STATIC_IP }}"

        # Delete existing container if it exists
        if az container show --resource-group "$RESOURCE_GROUP" --name "$CONTAINER_NAME" &> /dev/null; then
          echo "Container $CONTAINER_NAME exists. Deleting..."
          az container delete --resource-group "$RESOURCE_GROUP" --name "$CONTAINER_NAME" --yes
        else
          echo "No existing container found."
        fi

        # Deploy with Static IP
        az container create \
          --resource-group "$RESOURCE_GROUP" \
          --name "$CONTAINER_NAME" \
          --image "${{ secrets.DOCKERHUB_USERNAME }}/chakshu-chakshu:latest" \
          --cpu 4 --memory 16 \
          --dns-name-label "chakshu-demo" \
          --ports 8000 80 \
          --os-type Linux \
          --restart-policy Always \
          --registry-login-server "index.docker.io" \
          --registry-username "${{ secrets.DOCKERHUB_USERNAME }}" \
          --registry-password "${{ secrets.DOCKERHUB_PASSWORD }}" \
          --public-ip-address "$STATIC_IP_NAME" \
          --environment-variables \
            DB_NAME="${{ secrets.DB_NAME }}" \
            DB_USER="${{ secrets.DB_USER }}" \
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            DB_HOST="${{ secrets.DB_HOST }}" \
            DB_PORT="${{ secrets.DB_PORT }}" \
            DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}"

    - name: Cleanup Docker Cache
      run: |
        docker system prune -af
