name: Build and Push Docker Image to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Docker
      run: |
        sudo apt-get -qq update
        sudo apt-get -y -qq install \
          docker-ce docker-ce-cli containerd.io \
          docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin

    - name: Verify Docker Installation
      run: |
        docker version
        docker compose version

    - name: Build Docker Image
      run: |
        docker compose build

    - name: Save Docker Image as Tar
      run: |
        docker save -o chakshuv1.tar chakshuv1

    - name: Upload Docker Tar to Azure Blob Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az storage blob upload --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} --container-name docker-images --name chakshuv1.tar --file chakshuv1.tar --auth-mode key
