name: Build and Push Multiple Docker Images to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Larger runner with more disk space

    steps:
    # 1️⃣ Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Install Docker and Docker-Compose
    - name: Install Docker & Docker-Compose
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        docker --version
        docker compose version

    # 3️⃣ Build Docker Images
    - name: Build Docker Images
      run: |
        docker compose build   # Build local images (Django, Node)

    # 4️⃣ List Docker Images (for verification)
    - name: List Docker Images
      run: |
        docker images

    # 5️⃣ Log in to Docker Hub
    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # 6️⃣ Tag Docker Images for Docker Hub
    - name: Tag Docker Images
      run: |
        # Define Docker Hub username
        USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
        
        # Tag each image with Docker Hub repo
        docker tag chakshu-chakshu:latest $USERNAME/chakshu-chakshu:latest
        docker tag chakshu-node:latest $USERNAME/chakshu-node:latest

    # 7️⃣ Push Docker Images to Docker Hub
    - name: Push Docker Images to Docker Hub
      run: |
        USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
        
        # Push each image to Docker Hub
        docker push $USERNAME/chakshu-chakshu:latest
        docker push $USERNAME/chakshu-node:latest

    # 8️⃣ Tag Docker Images with Version (Optional)
    - name: Tag Docker Images with Version
      run: |
        USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
        VERSION="$(date +%Y%m%d%H%M%S)"
        
        # Tag images with version
        docker tag $USERNAME/chakshu-chakshu:latest $USERNAME/chakshu-chakshu:$VERSION
        docker tag $USERNAME/chakshu-node:latest $USERNAME/chakshu-node:$VERSION
        
        # Push versioned tags
        docker push $USERNAME/chakshu-chakshu:$VERSION
        docker push $USERNAME/chakshu-node:$VERSION

    # 9️⃣ Clean up Docker Cache (optional)
    - name: Cleanup Docker Cache
      run: |
        docker system prune -af
