name: Build and Push Docker-Compose Images with Ollama + LLaVA to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Docker & Docker-Compose
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        docker --version
        docker-compose version

    - name: Build Docker-Compose Stack
      run: |
        docker-compose build

    - name: List Docker Images
      run: |
        docker images

    - name: Save Docker Images to TAR
      run: |
        docker save -o chakshuv1.tar $(docker images --format "{{.Repository}}:{{.Tag}}" | grep -E "app|ollama")

    - name: Upload Docker Image to Blob Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --container-name docker-images \
            --file chakshuv1.tar \
            --name chakshuv1.tar
